name: 'ectomigo'
description: 'Measure the impact of database schema changes before you merge'
inputs:
  token:
    description: 'GitHub auth token'
    required: true
  migration_paths:
    description: 'process any changed files matching these comma-separated globs'
    required: false
  ignore_paths:
    description: 'ignore files matching these comma-separated globs while indexing'
    required: false
  patterns:
    description: 'JSON mapping named data access patterns to glob arrays, e.g. {"massive": ["**/*"]}'
    required: false
  main_branches:
    description: 'matches found in these branches will be reported to other repositories'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'database'
  color: 'white'
