name: ectomigo github test
# on: [push, pull_request]
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout
      - uses: ./
        name: test
        if: success()
        with:
          migration_paths: test/migrations/**/*
          token: ${{ secrets.GITHUB_TOKEN }}
